---
- hosts: webserver
  become: yes
  tasks:
  - name: Create a webserver
    apt:
     name: "{{item}}" 
     state: present
    when: ansible_os_family=="redhat" 
    loop:
    - tree
    - apache2
    - wget
    - python3
    - gnome-chess
    