---
- hosts: webserver
  become: yes
  tasks:
  - name: Create a webserver
    apt:
     name: "{{webserver}}"
     state: present

  - name: Start the webserver
    service:
     name: "{{webserver}}"
     state: started    